# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.16.13


# Mod Properties
mod_version=1.1.13
maven_group=net.nerdorg.minehop
archives_base_name=minehop-lite

# Dependencies
fabric_version=0.138.4+1.21.10
cloth_version=20.0.149
modmenu_version=16.0.0

# Misc
devUser=Gordon_Freeman